### ISSUE TITLE
Support Kotlin/Native 0.8

### ISSUE THREAD

**Issue by joelhandwell** [JetBrains/kotlin-native-calculator-sample#9]
Kotlin/Native 0.8 has been released and this repo can apply it.

**Comment by SvyatoslavScherbina** [comment]
This sample is outdated. Please see e.g. https://github.com/Kotlin/kmm-basic-sample instead.
More Kotlin Multiplatform Mobile samples can be found here: https://kotlinlang.org/docs/kmm-samples.html.
